version: "3.5"
services:
  nginx_proxy:
    image: hatlonely/nginx_proxy:1.0.0
    hostname: nginx_proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    volumes:
      - "${HOME}/var/docker/nginx_proxy/log:/var/log/nginx_proxy"
      - "${HOME}/var/docker/nginx_proxy/run:/var/run"
    networks:
      - nginx_proxynet
networks:
  nginx_proxynet:
    name: nginx_proxynet
