version: "3.5"
services:
  nginx:
    image: hatlonely/nginx:1.0.0
    hostname: nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6000:80"
    volumes:
      - "${HOME}/var/docker/nginx/log:/var/log/nginx"
      - "${HOME}/var/docker/nginx/run:/var/run"
    networks:
      - nginxnet
      - kibananet
      - grafananet
      - jenkinsnet
      - wordpressnet
      - chronografnet
      - vue-accountnet
      - go-accountnet
      - go-cloudnet
networks:
  nginxnet:
    name: nginxnet
  kibananet:
    external: true
    name: kibananet
  grafananet:
    external: true
    name: grafananet
  jenkinsnet:
    external: true
    name: jenkinsnet
  wordpressnet:
    external: true
    name: wordpressnet
  chronografnet:
    external: true
    name: chronografnet
  vue-accountnet:
    external: true
    name: vue-accountnet
  go-accountnet:
    external: true
    name: go-accountnet
  go-cloudnet:
    external: true
    name: go-cloudnet
