version: "3.5"
services:
  chronograf:
    image: chronograf:1.5.0.1-alpine
    hostname: chronograf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8888:8888"
    volumes:
      - "${HOME}/var/docker/chronograf/data:/var/lib/chronograf"
    networks:
      - chronografnet
      - influxdbnet
      - kapacitornet
networks:
  chronografnet:
    name: chronografnet
  influxdbnet:
    external: true
    name: influxdbnet
  kapacitornet:
    external: true
    name: kapacitornet
