version: "3.5"
services:
  influxdb:
    image: influxdb:1.7.6-alpine
    hostname: influxdb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8086:8086"
      - "2003:2003"
    volumes:
      - "${HOME}/var/docker/influxdb/data:/var/lib/influxdb"
      - "./influxdb.conf:/etc/influxdb/influxdb.conf"
    networks:
      - influxdbnet
networks:
  influxdbnet:
    name: influxdbnet
