version: "3.5"
services:
  redis:
    image: hatlonely/redis:1.0.0
    hostname: redis
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"
    volumes:
      - "${HOME}/var/docker/redis/data:/data"
    networks:
      - redisnet
networks:
  redisnet:
    name: redisnet
